[[main]]
  identifier = "about"
  name = "Sobre"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Arquivos"
  url = "archive"
  weight = 2

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 3